# Generated by Django 5.1 on 2024-08-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adm_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
