# Generated by Django 5.1 on 2024-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_alter_student_adm_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
