# Generated by Django 5.1 on 2024-08-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0005_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='adm_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
